services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ["python", "main.py"]
    env_file:
      - path: .env
        required: false
    environment:
      DATABASE_URI: postgresql+asyncpg://develop:develop@db/develop
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
      POSTGRES_DB: develop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 50s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 1m20s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"

volumes:
  postgres_data:
