[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "Fast Api template project"
version = "0.1.0"
description = ""
authors = ["Nazarii"]
readme = "README.md"
package-mode = false
license = "MIT"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "~=0.115"
alembic = "~=1.15"
sqlalchemy = "~=2.0"
pydantic = { version="~=2.11", extras = ["email"] }
pydantic-settings = "~=2.9"
uvicorn = { version="~=0.34", extras = ["standard"] }
asyncpg = "~=0.30"
python-jose = "~=3.4"
cryptography = "~=44.0"
passlib = { version="~=1.7", extras = ["bcrypt"] }
python-multipart = "0.0.20"
python-slugify = "~=8.0"
httpx = "^0.28.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "~=8.3"
pytest-mock = "~=3.14"
pytest-cov = "~=6.1"
pytest-asyncio = "~=0.26"
black = "~=25.1"
isort = "~=6.0"
freezegun = "~=1.5"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
gunicorn = "~=23.0"

[tool.black]
line-length = 120
extend-exclude = "versions"
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
skip = ["versions", "venv"]
line_length = 120
include_trailing_comma = true
profile = "black"
known_third_party = "celery"

[tool.pytest.ini_options]
testpaths = ["tests", "integration"]
addopts = "-v -s -ra -q"
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = "ignore"
norecursedirs = ["docs", "build"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
