[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "Fast Api template project"
version = "0.1.0"
description = ""
authors = ["Nazarii"]
readme = "README.md"
package-mode = false
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "~=0.115"
alembic = "~=1.14"
sqlalchemy = "~=2.0"
pydantic = { version="~=2.10", extras = ["email"] }
pydantic-settings = "~=2.6"
uvicorn = { version="~=0.32", extras = ["standard"] }
asyncpg = "~=0.30"
python-jose = "~=3.4"
cryptography = "~=44.0"
passlib = { version="~=1.7", extras = ["bcrypt"] }
python-multipart = "^0.0.19"
python-slugify = "~=8.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "~=8.3"
black = "~=24.10"
isort = "~=5.13"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
gunicorn = "~=23.0"

[tool.black]
line-length = 120
extend-exclude = "versions"
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
skip = ["versions", "venv"]
line_length = 120
include_trailing_comma = true
profile = "black"
known_third_party = "celery"

[tool.pytest.ini_options]
testpaths = ["tests", "integration"]
addopts = "-v -ra -q"
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
minversion = "6.0"
filterwarnings = "ignore"
norecursedirs = ["docs", "build"]
