[tool.poetry]
name = "fastapi-template"
version = "0.1.0"
description = ""
authors = ["bandirom <bandirom@ukr.net>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
uvicorn = {extras = ["standard"], version = "~=0.20"}
fastapi = "~=0.88"
tortoise-orm = {extras = ["asyncpg"], version = "~=0.19"}
aerich = "~=0.7"
email-validator = "~=1.3"
fastapi-jwt-auth = "~=0.5.0"


[tool.poetry.group.test.dependencies]
coverage = "~=6.5"
pytest = "~=7.2"
pytest-mock = "~=3.10"
black = "~=22.12"
isort = "~=5.11"

[tool.poetry.group.prod.dependencies]
gunicorn = "~=20.1"

[tool.aerich]
tortoise_orm = "main.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
skip = "migrations"
line_length = 110
include_trailing_comma = true
profile = "black"

[tool.black]
line-length = 110
exclude = "migrations"
skip-string-normalization = true
