name: Tests
on:
  push:
    branches:

jobs:
  tests:
    name: run pytest
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: pytest
        run:
          pytest
  black:
    name: run black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          pip install black
      - name: black
#        run: black . --check
        run: black .
  isort:
    name: run isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          pip install isort
      - name: isort
        run: isort . --check
