name: Tests

on:
  push:
    branches:
      - '*'

env:
  POETRY_VIRTUALENVS_CREATE: false
  DATABASE_URI: 'postgresql+asyncpg://fastapi:postgres_password@localhost:5432/template'

jobs:
  tests:
    name: run pytest
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_USER: fastapi
          POSTGRES_DB: template
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev --no-interaction --no-ansi
      - name: Run pytest
        run: pytest

  black:
    name: run black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Black
        run: pip install black
      - name: Check formatting with Black
        run: black . --check

  isort:
    name: run isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install isort
        run: pip install isort
      - name: Check import sorting
        run: isort . --check

  alembic_check:
    name: run alembic check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_USER: fastapi
          POSTGRES_DB: template
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-ansi
      - name: Apply migrations
        run: alembic upgrade head
      - name: Check migrations
        run: alembic check
