name: Tests
on:
  push:
    branches:
      - *
jobs:
  tests:
    name: run pytest
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: pytest
        run:
          pytest